services:
  valutaclient:
    image: ${DOCKER_REGISTRY-}valutaclient
    build:
      context: .
      dockerfile: ValutaClient/Dockerfile

  seq:
    image: datalust/seq
    ports:
      - 5341:5341
      - 5342:80
    environment:
      - ACCEPT_EULA=Y

  zipkin:
    image: openzipkin/zipkin
    ports:
      - 9411:9411

  rmq:
    image: rabbitmq:management
    ports:
      - 5672:5672
      - 15672:15672
    environment:
      - RABBITMQ_DEFAULT_USER=application
      - RABBITMQ_DEFAULT_PASS=pepsi

  mssql:
    image: mcr.microsoft.com/mssql/server:2022-latest
    ports:
     - 1433:1433
    environment:
      MSSQL_SA_PASSWORD: "S3cr3tP4sSw0rd#123"
      ACCEPT_EULA: "Y"
    volumes:             
     - database-data:/var/opt/mssql

volumes:
 database-data:  
